### ISSUE TITLE
Suggestion: Can you change the icons of List, Notifications and some other

### ISSUE THREAD

**Issue by DishankJ** [RaitaroH/MyAnimeList-DeepDark#16]
The current icons on MAL home page such as list and notification look very old, I don't think so it would be a big task. Also, keep up the good work.

**Comment by RaitaroH** [comment]
I mean I could but at this point they might do a redesign for the site so that work would be for nothing.

**Comment by DishankJ** [comment]
I don't think so MAL will be getting a new UI ot redesign anytime soon.

**Comment by ShadyDeth** [comment]
Thought I would give this a try but hit a roadblock with Stylus not allowing `@font-face` use. This stops you from loading web fonts. Since MAL currently uses FontAwesome web font, which is how the icon color changes when you change the theme. I have an idea for svg's and will test when I get some free time.

Other than that the only way would be to make a color set of png's for each theme and that would take time.
