### ISSUE TITLE
[Off-topic question] How would the ideal userstyles sharing platform be like ?

### ISSUE THREAD

**Issue by KaKi87** [RaitaroH/MyAnimeList-DeepDark#19]
Hello,

Despite userstyles.org slowly dies, this website is still the leading userstyles sharing platform, and despite many tried to replace it, they all failed.

As I am also planning to try, I would firstly like to ask actual userstyles developers, like you : what would you expect from a userstyles sharing platform which aims to replace userstyles.org ?

Thanks.

**Comment by RaitaroH** [comment]
I already saw your discussion with Joker on the topic. I don't really have much to add. I don't think it will help you to ask developers about this stuff because we are not the people who will use your site for the most part.

Personally I don't care about such platforms, because if I need an userstyle then I can find it on github, or if I don't then I can make it myself. I don't care of having my userstyles available in a bunch of places because is a hassle; automatic mirroring from github is the best choice, or like in userstyle.world just a link to github itself.
