### ISSUE TITLE
Install of script breaks Stylus

### ISSUE THREAD

**Issue by ShadyDeth** [RaitaroH/MyAnimeList-DeepDark#7]
Since the commit of 1.4.9 #5 a new install of the script breaks Stylus on Chrome and Firefox for me. You have to disable and re-enable the addon for it to work again. It also breaks the Stylus editor from working at all on this script.

It does not like this part of the code `@-moz-document /*[[reach]]*/ {`

Would like to see if you are having this issue also.

**Comment by RaitaroH** [comment]
Ah, yes you are right. It seems the bug is right ![here](https://github.com/RaitaroH/MyAnimeList-DeepDark/commit/c8c5c93383ad4c1602da73c2be2679bb2623b2d7#diff-29a3b10c05e0de894360ee21c4d31f79R227) 
It seems that passing the domain or regexp breaks stylus. I looked a bit at the documentation for Stylus I can't find a way to make what the guy wanted an option. As far as I can see there is no way to pass a var to the domain thing without having stylus hiccup. The theme still works so I never noticed.

@Mottie might know if this is just not implemented or if simply a bug.

**Comment by RaitaroH** [comment]
I just fixed the problem in https://github.com/RaitaroH/MyAnimeList-DeepDark/commit/7ecf308fa28e4712e6d5ef833a66bce1948daf75.
Now it works fine and you can open the editor.

**Comment by Mottie** [comment]
Adding a placeholder inside the `@document` won't ever work because those blocks are not stored nor used along with the CSS. This is because only Firefox was supporting a prefixed `@-moz-document`; fo r which support is not disabled by default.

I can't think of any workaround for this. If you really need it, please open an [issue in the Stylus repo](https://github.com/openstyles/stylus/issues).
